[package]
name = "c99"
version = "0.1.1"
authors = ["Vojtech Kral <vojtech@kral.hk>"]
license = "BSD-2-Clause"

description = "C99 types for easier interop"
homepage = "https://github.com/vojtechkral/rust-c99"
repository = "https://github.com/vojtechkral/rust-c99"

build = "build.rs"
